#!/bin/bash

POLLING_INTERVAL=6 # Default to 6 hours

CRONTAB=$( \
	crontab -l \
	| grep --perl-regexp "/covid-scripts/get-all" \
	| sed --regexp-extended 's/\s+/\t/g' \
)

CRON_HOUR=$( printf "%s" "${CRONTAB}" | cut --field=2 )
if [[ ! -z "${CRON_HOUR}" ]] ; then
	CRON_INTERVAL=0
	if [[ "${CRON_HOUR}" =~ ^[0-9]+$ ]] ; then
		CRON_INTERVAL=24
	elif [[ "${CRON_HOUR}" =~ ^[*]$ ]] ; then
		CRON_INTERVAL=1
	elif [[ "${CRON_HOUR}" =~ ^[*]/[0-9]+$ ]] ; then
		CRON_INTERVAL=$( printf "%s" "${CRON_HOUR}" | cut --delimiter="/" --field=2 )
	fi

	if [[ "${CRON_INTERVAL}" -gt 0 ]] ; then
		POLLING_INTERVAL="${CRON_INTERVAL}"
	fi

fi

printf "%d" ${POLLING_INTERVAL}

