#!/bin/bash

DATA_URL="$1"
DATA_TAG="$2"
DATESTAMP="$3"
DATA_DIR="$4"

DATA_PREFIX="${DATA_DIR}/data/${DATA_TAG}-"

URL_OUT="${DATA_PREFIX}${DATESTAMP}.url.txt"
DATA_OUT="${DATA_PREFIX}${DATESTAMP}.json"
WARC_OUT="${DATA_PREFIX}${DATESTAMP}"

echo "${DATA_URL}" > "${URL_OUT}"
wget --output-document="${DATA_OUT}" --warc-file="${WARC_OUT}" "${DATA_URL}"

echo "Completed ${DATA_TAG} data dump: " $( date )

