#!/bin/bash

declare -a N_ARGV=()
declare -a N_OBJS=()
declare -A N_PARAMS=()
declare -A N_SWITCHES=()
while [ $# -ge 1 ] ; do
	N_ARGV=(${N_ARGV[@]} "$1")
	if [[ "$1" =~ ^--([^=]+)(=(.*))?$ ]] ; then
		KEY="${BASH_REMATCH[1]}"
		N_SWITCHES["${KEY}"]="${BASH_REMATCH[0]}"	

		VALUE="${BASH_REMATCH[1]}"
		if [[ ! -z "${BASH_REMATCH[2]}" ]] ; then
			VALUE="${BASH_REMATCH[3]}"
		fi
		N_PARAMS[${KEY}]="${VALUE}"
	else
		N_OBJS=(${N_OBJS[@]} "$1")
	fi

	shift
done

# NOOP
if [[ ! -z "${N_PARAMS[noop-verbose]}" ]] ; then
	if [[ "${N_PARAMS[noop-verbose]}" = "debug" ]] ; then
		declare -p N_ARGV
		declare -p N_OBJS
		declare -p N_SWITCHES
		declare -p N_PARAMS
	else
		echo "${N_ARGV[@]}"
	fi
fi


